version: "3.9"

services:
  master:                             # Master Node
    image: hadoop-master-image
    build:
      context: .
      dockerfile: ./master/Dockerfile # Путь к Dockerfile образа управляющего узла
    ports:
      - '9870:9870'                   # Namenode
      - '8088:8088'                   # Resource Manager
      - "19888:19888"                 # History Server
    container_name: master
    volumes: 
      - ../HomeWork_2/app:/home/bigdata/app       # jar files
      - ../HomeWork_2/data:/home/bigdata/data     # data to copy to HDFS
    networks:
      - hd-network

  worker:                             # Worker Node
    image: hadoop-worker-image
    build:
      context: .
      dockerfile: ./worker/Dockerfile # Путь к Dockerfile образа вычислительного узла
    networks:
      - hd-network

networks:
  hd-network:                         # Network
    driver: bridge                    # Тип сети
    ipam:
      config:
        - subnet:  172.18.0.0/24      # Определение пространства адресов сети